In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
data = pd.read_csv('Churn_Modelling.csv')

In [ ]:

data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
trans = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(trans.fit_transform(X))

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
X[:,4] = encoder.fit_transform(X[:,4]) 

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 22)


In [ ]:
X_train[0,:]

array([0.0, 0.0, 1.0, 608, 0, 56, 5, 0.0, 2, 0, 1, 153810.41],
      dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
ss =StandardScaler()
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [ ]:
model = tf.keras.models.Sequential()

In [ ]:
model.add(tf.keras.layers.Dense(6,'relu'))

In [ ]:
model.add(tf.keras.layers.Dense(6,'relu'))

In [ ]:
model.add(tf.keras.layers.Dense(1,'sigmoid'))

In [ ]:
model.compile('adam','binary_crossentropy',['accuracy'])

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7384
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4582 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4429 - accuracy: 0.7974
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4347 - accuracy: 0.8037
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4290 - accuracy: 0.8089
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8133
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4208 - accuracy: 0.8190
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4168 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4132 - accuracy: 0.8255
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4098 - accura

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred = (y_pred > 0.5)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.859